@url=https://127.0.0.1:5001/api/person

###
# Get all the persons
GET {{url}}

###
# Get a specific person
GET {{url}}/358f4598-370f-4360-9a10-1a4b1693536e

###
# Add a person
POST {{url}}
Content-Type: application/json

{
    "FirstName": "Nemanja",
    "LastName": "Beric",
    "Gender": 0,
    "BandNumber": 1
}

###
# Update a specific person
PUT {{url}}/358f4598-370f-4360-9a10-1a4b1693536e
Content-Type: application/json

{
    "PersonId": "358f4598-370f-4360-9a10-1a4b1693536e",
    "FirstName": "Noemie",
    "LastName": "Dendieu",
    "Gender": 1,
    "BandNumber": 0,
    "Birthday": "2020-03-19T23:00:00.000Z"
}

###
# Delete a specific person
DELETE {{url}}/b48bcdb9-aacb-4aa6-9746-2ed96eda9285